// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/personal-site/Broadsheet.tsx": () => import("../components/mockups/personal-site/Broadsheet.tsx"),
  "./components/mockups/personal-site/Literary.tsx": () => import("../components/mockups/personal-site/Literary.tsx"),
  "./components/mockups/personal-site/ModernEditorial.tsx": () => import("../components/mockups/personal-site/ModernEditorial.tsx")
};
